### ISSUE TITLE
Trouble installing cosmosDB

### ISSUE THREAD

**Issue by Rogue899** [Microsoft/vscode-cosmosdb#1083]
nothing happens when i press install

**Comment by StephenWeatherford** [comment]
@Rogue899 Thanks for filing an issue.  I've never heard of this before.  This is what happens when I click install:
![installdocker](https://user-images.githubusercontent.com/6913354/55442160-4ab45900-5562-11e9-8e2d-a479266ee675.gif)
Does anything happen at all when you click the install button, or is it really doing absolutely nothing?

Also, do you have the most recent version of vscode, and can you try installing some other extensions and see if that works?

Thanks!
Stephen

**Comment by StephenWeatherford** [comment]
Also, here's something to try, if maybe it's stuck with a previous or partially installed version:
Go to your home folder (%USERPROFILE% or ~), then to {.vscode,.vscode-insiders}\extensions and delete any folders containing vscode-cosmosdb, then restart vscode and try installing again.
