### ISSUE TITLE
Need a method to pass SSL information when creating connection to a Mongo instance

### ISSUE THREAD

**Issue by yergi** [microsoft/vscode-cosmosdb#1147]
Per discussion in #1104, opening a new issue as this is a bit more specific use case. From my comment there:

> Since SSL is a special case and its arguments can be passed via the .connect() method from the Node driver, would it make more sense to have a separate setting for those args? Perhaps a mongo.ssl setting that could be an object that needs to be passed to the server option, which constructs a [Server instance](https://mongodb.github.io/node-mongodb-native/2.0/api/Server.html). This would avoid having to pass the SSL flags in the shell on every call to the database.

> The main difficulty I see with that is that the sslCA, sslKey, and sslCert options can't take a filepath str, the file has to be read and the contents passed.

**Comment by nturinski** [comment]
Does this PR https://github.com/microsoft/vscode-cosmosdb/pull/1162 resolve your issue?  You should be able to use this setting to pass arguments to the mongo shell.

If this doesn't resolve your issue, would you be interested in contributing?  It's difficult for us to implement this because it's an uncommon use case scenario for us.
