### ISSUE TITLE
Action to select and filter the subscription from the explorer

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cosmosdb#1278]
Hi VS Code dev here 👋

It would be convenient if there is an action (in context menu) to filter the selected subscription

**Comment by nturinski** [comment]
Just to clarify, you mean if you were to right-click the subscription, you are suggesting to have a context menu item that says "Filter" rather than using the in-line button to open the filter menu?

![image](https://user-images.githubusercontent.com/5290572/72195652-44dc8580-33c8-11ea-921e-b2b062f7d325.png)

**Comment by sandy081** [comment]
I mean a context menu action item (right click on subscription) `Filter` that will remove from the view.

**Comment by nturinski** [comment]
We're currently in the process of redesigning the UI for subscription tree items.  I'll close this issue in favor of [this](https://github.com/microsoft/vscode-azuretools/issues/350) one.
