### ISSUE TITLE
Create Postgres Account - Default Setup

### ISSUE THREAD

**Issue by neelip** [microsoft/vscode-cosmosdb#1355]

**Comment by neelip** [comment]
1. Postgres API allows 4 different kinds of account creation --> Default, Restore, GeoRestore and Replica. Should we just support default for now?
2. For the Default create mode, there are few optional properties --> version, storage profile, sku, tags. How do we want to handle them?

**Comment by neelip** [comment]
Should we store the username and password as the user inputs these to create an account? Or we only use these inputs to create an account and then late on they have to re-enter these details to access the databases?

**Comment by wwlorey** [comment]
> Should we store the username and password as the user inputs these to create an account? Or we only use these inputs to create an account and then late on they have to re-enter these details to access the databases?

I think it would make sense to cache the username and password when the account is created so they don't have to be entered multiple times. We should be able to reuse [this function](https://github.com/microsoft/vscode-cosmosdb/blob/fd1bace91597078193ca8b3106f6c147cc76e1a4/src/postgres/tree/PostgresDatabaseTreeItem.ts#L88) with some tweaks. It may need to be moved to `PostgresServerTreeItem` since we won't have access to databases before creating the server
