### ISSUE TITLE
Make sure "Execute Query" codelens isn't annoying

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-cosmosdb#1455]
In https://github.com/microsoft/vscode-cosmosdb/pull/1444, we added an "Execute Query" codelens to all "sql" files, but I think there's a risk of that codelens showing up in sql files unrelated to our PostgreSQL database support and annoying/confusing users. We might want to investigate having our own unique file type that "extends" sql so that _only_ the right people get the codelens but we maintain existing support for sql colorization (I'm _pretty sure_ that's possible, but not 100%)

**Comment by wwlorey** [comment]
So I found that it is possible to have sql syntax coloring for other file extensions using this setting:

```json
"files.associations": {
    "*.psql": "sql"
}
```
<img width="263" alt="Screen Shot 2020-05-15 at 1 04 36 PM" src="https://user-images.githubusercontent.com/22795803/82091676-a2514d80-96ac-11ea-8ec8-7bdb83502a55.png">

But unfortunately there's some weird behavior with the codelens. Because this aliases `psql` files to `sql`, the codelens doesn't apply once this setting is set. I'll keep looking for another way to take care of this
