### ISSUE TITLE
There is no error when inputting a duplicate account name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1506]
**OS:** Mac
**Build Version:** 20200522.22

**Repro step:**

1. Create a server for PostgreSQL with the name "test1"
2. Create a new server for PostgreSQL --> type a duplicate name "test1"
3. Check the result

**Expect:**
There is an error "The account name is already exists".

**Actual:**
There is no error when inputting a duplicate account name.

**Comment by wwlorey** [comment]
We do check existing servers when validating new server names. 

<img width="630" alt="Screen Shot 2020-05-26 at 8 40 31 AM" src="https://user-images.githubusercontent.com/22795803/82920921-c32b6580-9f2c-11ea-9fff-1ceb707fd602.png">

Did the "test1" server finish creating before you tried creating a duplicate? We don't validate against the servers still being created since they don't exist in Azure yet

**Comment by v-mengwe** [comment]
This issue only reproduce on Mac.
![image](https://user-images.githubusercontent.com/62053665/82969031-3d2d1e80-a001-11ea-9256-e5cbfe63fabc.png)

**Comment by wwlorey** [comment]
I was able to repro this. It happens for me once every ~20 attempts to enter an existing name. 

When it fails to display an existing name error, `validatePostgresServerName` still detects that the name already exists and returns correctly. So this problem may be related to `showInputBox`

**Comment by wwlorey** [comment]
Closing as won't fix
