### ISSUE TITLE
I'm getting this error while opening a document from cosmosdb

### ISSUE THREAD

**Issue by mercer** [microsoft/vscode-cosmosdb#1743]
Does this occur consistently? YEs
Repro steps:

1. Not sure, hapens with our document source
1. First time i'm using the extension
1. I can open other documents from other collections just fine

Action: cosmosDB.openDocument
Error type: EntryNotFound
Error Message: EntryNotFound (FileSystemError): azureDatabases:/REDACTED-cosmos-document.json?id=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.DocumentDB/databaseAccounts/SOME-COSMOSDB/SOMEPATH/MOREPATH/$Documents/wRITAP+mLPREDACTED

Version: 0.15.0
OS: linux
OS Release: 5.8.0-7625-generic
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6599:715
```

</details>

**Comment by neelip** [comment]
Does your document title contain special characters?

**Comment by mercer** [comment]
No, I don't think so

**Comment by eglyph** [comment]
Having the same issue.  It seems it's related to a particular database somehow, because another database under the same account and the same settings works just fine. No special characters or anything like that in names or documents. Details are below:

Does this occur consistently? Yes
Repro steps:

1. Install the extension, attach a CosmosDb database using a primary connection string
2. Browse collections within a database in a tree explorer, expand a collection and observe stored documents ids.
3. Click on a document in a tree explorer.

Expected behavior: a document is opened.
Actual behavior: an error message is displayed. 

Action: cosmosDB.openDocument
Error type: EntryNotFound
Error Message: EntryNotFound (FileSystemError): azureDatabases:/<redacted-document-id>-cosmos-document.json?id=<redacted>==

Version: 0.15.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6800:388
```

</details>
