### ISSUE TITLE
Failed to open document(s) via Visual Studio Code extension

### ISSUE THREAD

**Issue by oadrian2** [microsoft/vscode-cosmosdb#1828]
Does this occur consistently? Yes
Repro steps:

1. Connect via Visual Studio Code Azure Database Extensions.
2. Click on a document to open it. Doesn't apply to all documents, but most of them.

Action: cosmosDB.openDocument
Error type: Error
Error Message: cannot open azureDatabases:/oXWGaZHWtDuwpjVotbdXe-cosmos-document.json?id%3D%2Fsubscriptions%2F156452f6-053e-444e-9f7c-2bef1346fbcc%2FresourceGroups%2Farm-vscode%2Fproviders%2FMicrosoft.DocumentDB%2FdatabaseAccounts%2Fcosmos-oursongmaps%2FMaps%2FTokens%2F%24Documents%2FQXo-AImHSy%2BaAAAAAAAAAA%3D%3D. Detail: Unable to read file 'azureDatabases:/oXWGaZHWtDuwpjVotbdXe-cosmos-document.json?id=/subscriptions/156452f6-053e-444e-9f7c-2bef1346fbcc/resourceGroups/arm-vscode/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-oursongmaps/Maps/Tokens/$Documents/QXo-AImHSy+aAAAAAAAAAA==' (Error: Unable to resolve non-existing file 'azureDatabases:/oXWGaZHWtDuwpjVotbdXe-cosmos-document.json?id=/subscriptions/156452f6-053e-444e-9f7c-2bef1346fbcc/resourceGroups/arm-vscode/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-oursongmaps/Maps/Tokens/$Documents/QXo-AImHSy+aAAAAAAAAAA==')

Version: 0.15.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:2099:109144
```

</details>

**Comment by nturinski** [comment]
Unfortunately we can't repro this issue with these steps.  Do you happen to see any pattern between the files that are working and the ones that aren't?  Perhaps the database that they're in or the type of data of those documents?  The error says it can't resolve the non-existing file which makes me think that it's not download properly.  Are the documents fairly large by chance?

**Comment by pseudoramble** [comment]
Sorry to resurrect a thread, but I am seeing this same issue as well. I have some more details that I hope will lead to an idea. 

My setup is similar to the initial description. One big detail I can add is that I'm connecting to the emulator but I'm not attaching it like an emulator because I change the AccountKey to access it. So I attach a database via https://localhost:8081. The plugin can list all of the databases and collections, as well as the names of the documents.

Also, this error was not happening a week or so ago, and I haven't changed how the documents work. So I'm unsure about what could be off.

A few details I can give (though I don't know if it's super helpful):

1. I deleted and recreated the document through our normal pattern and it was still unable to open it.
2. I created a new document of the same type in the same collection and see the same problem.
3. The plugin can open some larger and smaller documents than the one it cannot open.
4. The plugin can open documents in the same database but different collections.
5. I can load these documents through our API's just fine. So it doesn't seem to be a connection or Cosmos Emulator issue.
