### ISSUE TITLE
[Suggestion] It would be better if can select a specified PostgreSQL account when executing "PostgreSQL: Create Function Query..." from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1946]
**OS:** Windows
**Build Version:** 20211117.4
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> PostgreSQL: Delete Function... -> Select subscription -> Select Account -> Select Database -> Select Function to delete it.
2. F1 -> PostgreSQL: Create Function Query... .
3. Check whether can select a PostgreSQL account in the next step.

**Actual:**
Can not to select a PostgreSQL account in the next step.

**Suggestion:**
It would be better if can select a specified PostgreSQL account when executing "PostgreSQL: Create Function Query..." from command palette.

**More Info:**
1. This issue also reproduces when creating a stored procedures query.
2. Create a function for the account which contained connected database directly after executing `PostgreSQL: Create Function Query... ` command.

**Comment by nturinski** [comment]
Closing as by-design.  This behavior was actually intentional.  We assume that when a user calls `Create Function Query`, they would want to run it on the currently connected database.  

The reason we don't do this for delete is because it would be unusual for a user to delete the database that they are connected to at the time.
