### ISSUE TITLE
Plus sign to expand a Cosmos DB account not visible

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#197]
vs code insiders nightly build
v0.2.0

Notice that the second Cosmos instance in the tree below has no plus sign. This just started happening in the latest extension update.

![image](https://user-images.githubusercontent.com/1202528/32761959-75b2ce1a-c8c4-11e7-8439-901a7d183ba1.png)

**Comment by EricJizbaMSFT** [comment]
@johnpapa We only support 'graph', 'mongo' and 'documentdb' at the moment. Is that one table api?

See https://github.com/Microsoft/vscode-cosmosdb/issues/77

**Comment by johnpapa** [comment]
I "think" i selected `Mongo` each time i created these databases. The connection string in the portal shows `mongo:// ...`

is there some other setting i should check>

**Comment by EricJizbaMSFT** [comment]
I'm pretty sure the only way the portal differentiates mongo/docdb/graph/table is through this tag:

![screen shot 2017-11-14 at 4 27 48 pm](https://user-images.githubusercontent.com/11282622/32812235-dc3656c2-c958-11e7-91d5-d564ae606038.png)
![screen shot 2017-11-14 at 4 28 03 pm](https://user-images.githubusercontent.com/11282622/32812237-ddc87060-c958-11e7-811f-537ace7f6926.png)

Do you still have that tag set to mongo?

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/230

I added an error message to table accounts so that it's less confusing:
<img width="286" alt="screen shot 2017-11-28 at 5 14 39 pm" src="https://user-images.githubusercontent.com/11282622/33352853-c33371c0-d45f-11e7-9563-e72c85752112.png">

I also added logic to default to 'DocumentDB' experience if the tag mentioned above is not set (since it is the only experience that should work in all cases).
