### ISSUE TITLE
MongoDB database version selection in creation

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-cosmosdb#1999]
There are 4 versions of MongoDB supported in CosmosDB right now. It is critical that a customer be able to select the version when they create the resource. The current VSCode database process creates a 3.6 version which is the oldest. Can the choices at least be "latest" and "default"?

**Comment by JasonYeMSFT** [comment]
This will be a challenge to us since major version MongoDB releases introduces a lot of breaking changes and it will be hard for a client tool to support multiple versions at the same time. In my opinion the extension should try to be up-to-date with the latest MongoDB driver and deprecate support to older versions of MongoDB in new extension releases. People who need to work with the older versions of MongoDB can install prior versions of the extension. Does that make sense to you?
