### ISSUE TITLE
The error is not clear when creating a Flexible PostgreSQL server with Azure China account

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2036]
**OS:** Win10
**Build Version:** 20220605.1

**Repro Steps:**
1. Sign in with the Azure China account.
2. Try to create a Flexible PostgreSQL server with "China North 3" region, an error occurs.
3. Check whether the error is clear or not.

**Expect:**
The error is clear, such as "The resource is not supported in Azure China cloud".

**Actual:**
The error is not clear.
![image](https://user-images.githubusercontent.com/45614674/172151766-d327c79a-542d-4c06-851f-b96f15e4f825.png)

**More Info:**
Fail to create a Flexible PostgreSQL server with "China East 2" region
![image](https://user-images.githubusercontent.com/45614674/172151956-503f7834-c6f6-4e5f-b0a2-5a9bafaf0d95.png)

**Comment by nturinski** [comment]
Since the error is coming from Azure, I don't think we should be catching it and displaying our own error. 

I believe that the first error is pretty clear. As for the 2nd one, I am not sure why the provisioning failed, but I don't think that this is something that we can do anything about. The service will have to fix this error.
