### ISSUE TITLE
There is no "+ Create new Database" command in the list when executing "Connect to a database" action

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#2093]
**OS:** All
**Azure Resource Extension Build Version:** 20220426.4 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Click "Connect to a database" in an opened Mongo Scrapbook -> Select a subscription -> Select "Azure CosmosDB" -> Select a resource.
2. Check whether there is a "+ Create new Database" command in the list or not.

**Expect:**
There is a "+ Create new Database" command in the list.
<img width="268" alt="Screen Shot 2022-04-27 at 14 47 37" src="https://user-images.githubusercontent.com/62053665/165467022-7c0a590e-8369-4acb-b140-0137e956ba58.png">

**Actual:**
There is no "+ Create new Database" command in the list.
<img width="242" alt="Screen Shot 2022-04-27 at 14 47 51" src="https://user-images.githubusercontent.com/62053665/165466957-e77285aa-69dd-424e-b60a-9558a20813d1.png">

**Comment by JasonYeMSFT** [comment]
Selecting the wrong resource type from the resource picker will lead to undefined behavior right now. The code internally assumes the object type of the correct resource type and lots of things could go wrong if that's not true. The ultimate solution is for the resource picker to filter out all irrelevant resources so that the assumption the code makes is always maintained. However, that needs to be done in the resource group extension and is beyond the scope of the extension.
