### ISSUE TITLE
The error is not clear when creating a database for PostgreSQL server without configuring firewall to connect to it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2162]
**OS:** Win10
**Build Version:** 20230822.5
**Regression:** Not a Regression

**Repro Steps:**
1. Create one PostgreSQL server.
2. Don't configure firewall to connect to this PostgreSQL server.
3. Try to create a database for the above PostgreSQL server, an error occurs.
4. Check whether the error is clear or not.

**Expect:**
The error is clear, such as "Fail to create database, please configure firewall to connect server first".

**Actual:**
The error is not clear.
1. The below error occurs when creating a database for PostgreSQL Single server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/4d7e3a9b-5654-4b32-b0ed-2f66ec19ad48)
2. Another error occurs when creating a database for PostgreSQL Flexible server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/5bc78528-a07e-45d1-bd89-81e96d29784f)

**More Info:**
This issue also reproduces on the current released extension v0.19.4.

**Comment by v-ruizh** [comment]
Verified this bug on a newer build 20230927.1, the error message changes. 
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/cafa26f0-3eea-4f9e-bf3e-8e0e9ea5b1e1)

**Comment by JasonYeMSFT** [comment]
@v-ruizh The message is only shown when the extension's detected IP is already in the firewall rules but still fails to connect. Since the extension can only add the detected IP to the firewall rule, there is no point trying to do it again. The messages suggests people to try it on Portal because it may have a better chance of setting the correct IP.
