### ISSUE TITLE
DNS for cosmos on privatelink not resolving via twingate resolver - linux

### ISSUE THREAD

**Issue by SteveDevOps** [microsoft/vscode-cosmosdb#2173]
We employ a zero trust network provider called [twingate](https://twingate.com). Our cosmosdb instances employ azure privatelink/private endpoint.  I can't access instance privately while using this extension. It forces me to the public interface where I am blocked by firewall. I know that the twingate setup is correct because I can nslookup and get the twingate address for it.  We have defined the public name, the privatelink name, and the private ip address inside of twingate resources. Is there something in this extension that is preventing OS level dns resolution of the cosmosdb name? I am running linux - pop_os 22.04. We are on cosmodb nosql serverless running sql api.

**Comment by SteveDevOps** [comment]
I have been informed this is a problem potentially on the twingate side.. so awaiting more info / closing for now. https://forum.twingate.com/t/failing-to-connect-to-resources-outside-of-the-browser-ie-cli-and-dev-tools/1015/2

**Comment by SteveDevOps** [comment]
Managed to get a support call in with Azure networking and twingate. Leaving this note in case someone else runs into this -- And maybe someone from the vscode team can explain / shed some light on requirements for request payload -- but connection to cosmosdb via databases extension didn't work for privatelink while on active twingate connection until we provided all four domains as resources in twingate -- from the associated zone file:

xxx.documents.azure.com
xxx.privatelink.azure.com

AND ALSO THE REGION ENDPOINT:
xxx-southcentralus.documents.azure.com
xxx-southcentralus.privatelink.documents.azure.com

and then finally the private IPs..

We were missing the **southcentralus** /region based endpoints defined as twingate resources as well. Why does vscode database extention require these endpoints? Thx!

**Comment by JasonYeMSFT** [comment]
Unfortunately, the database extension doesn't handle DNS resolution so for such kind of issues, there isn't much we can help. You will need to fix the network configuration by yourself.

I did read your links and I have a hypothesis. The documentation of Azure Cosmos DB says there are two kinds of regions for a Cosmos DB instance, a read region and a write region. It's said that write operations will be redirected to clusters in the write regions if the request goes to a read region. You might want to check if South Central US is indeed one of the write regions of your instance. If so, the client might be redirected to it. Since twingate doesn't recognize it, it delegates the connection to the normal network interface and exposes the public IP of the client.
