### ISSUE TITLE
Nothing shows under the PostgreSQL server after entering server credentials for it on another machine

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2194]
**OS:** Win10
**Build Version:** 20231006.1
**Regression:** Previous Release

**Repro Steps:**
1. Create one PostgreSQL server in VS Code.
2. Expand the above PostgreSQL server on another machine -> Enter server credentials with the right username and password.
3. Check whether the "Configure firewall to connect to..." shows under the PostgreSQL server or not.

**Expect:**
The "Configure firewall to connect to..." shows under the PostgreSQL server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/da4dd63f-4453-4718-b98d-4510bd7a27db)

**Actual:**
Nothing shows under the PostgreSQL server and a notification pops up.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/eb6fd057-c5ce-4bc7-96c9-b53fdc54decd)
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/e1119019-465d-43c8-a557-57427e4c0fe8)

**More Info:**
This issue does not reproduce on the current released extension v0.19.4.

**Comment by JasonYeMSFT** [comment]
This might be an intentional change. I noticed that it is possible to get the wrong IP address when the extension code attempts to add the firewall rule. Could you try going to Azure Portal and configure the firewall rule there and then try accessing the database. If that works, then we don't need to worry about this issue.
