### ISSUE TITLE
Fail to execute the stored procedure query named with the existing function name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2232]
**OS:** Win10
**Build Version:** 20240112.17

**Repro Steps:**
1. Create a PostgreSQL Flexible server.
2. Expand the PostgreSQL Flexible server -> postgre database -> Create a function "one" for this database.
3. Create a stored procedure query with name "one" -> Execute this query.
4. Check whether succeeds to execute the stored procedure query named with the existing function name or not.

**Expect:**
Succeeds to execute the stored procedure query named with the existing function name.

**Actual:**
Fail to execute the stored procedure query named with the existing function name.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/bf2644fb-d355-4495-95b8-841fbcf1df6a)

**More Info:**
1. This issue also reproduces for PostgreSQL Single server.
2. This issue also reproduces when executing the function query named with the existing stored procedure name.

**Comment by JasonYeMSFT** [comment]
Debugging the code reveals more details:
<img width="218" alt="image" src="https://github.com/microsoft/vscode-cosmosdb/assets/39359541/4d2fe0f6-678a-47d3-a0c9-89592d753f66">

In PostgreSQL, both `function`s and `procedure`s are different kinds of `routine`s. If a function with the same name exists, the error message indicates that the new procedure cannot be created because by doing so, it would effectively change the "kind" of the existing function to "procedure". The error is expected.
