### ISSUE TITLE
The wizard "Select a capacity model" will disappear after selecting "vCore cluster" option

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2427]
**OS:** Windows 10
**Build Version:** 20241116.1
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Select "Azure Databases: Create Server..." -> Select "Cosmos DB for MongoDB" -> Enter a name -> Select "vCore cluster" option.
2. Navigate to VS Code.
3. Check whether the wizard "Select a capacity model" still exists or not.

**Expect:**
The wizard "Select a capacity model" still exists.
![Image](https://github.com/user-attachments/assets/31a67881-24ac-4b63-82b4-609ca8e08e1a)

**Actual:**
The wizard "Select a capacity model" disappears.

**More Info:**
The wizard "Select a capacity model" still exists after selecting "Learn more..." option.

**Comment by sevoku** [comment]
This is unclear... selecting "Learn more..." should not make the wizard disappear, if that happens, it's a bug but I can't reproduce that. Selecting "vCore Cluster" behaviour is intended, the wizard stops there since there is currently no way to proceed from there. Users will need to read the documentation and come back. A full E2E experience to create MongoDB clusters will come with a later release.
