### ISSUE TITLE
Persisted connected node does not display Connected in its label on startup

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#481]

**Comment by EricJizbaMSFT** [comment]
This was somewhat intentional. I initially loaded the 'connected' node on startup, but noticed a negative effect on the tree. This is what the experience _should_ be if you expand a subscription node right after opening VS Code:
![test2](https://user-images.githubusercontent.com/11282622/38326500-cf6ce328-37fa-11e8-987a-46b901d0eabd.gif)

But this is what I noticed when I loaded the 'connected' node on startup:
![test](https://user-images.githubusercontent.com/11282622/38326493-cc300cbc-37fa-11e8-87e2-3004f8180d15.gif)
You'll notice the loading icon doesn't display.

With that in mind, I changed it to load the persisted node right before you execute a mongo command rather than on startup. I say we only fix this bug if we also fix the behavior above, which might not be an easy thing. Fine to move to the next milestone?
