### ISSUE TITLE
Mongodb connections are not securely persisted across workspaces

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#5]
Rather than using a workspace specific storage path to store connection strings, we should use the vscode secure storage that works across workspaces

**Comment by EricJizbaMSFT** [comment]
@fiveisprime @chrisdias Matt and I discussed no longer persisting connection strings at all. The Cosmos DB extension will list connections from Azure and we don't want to persist connection strings unless we can store them securely. If you confirm this behavior, I'll change this issue to something like "Don't persist connection strings"

Ideally we have secure storage, but per offline discussion we are not sure if/when that will be publicly available.

**Comment by fiveisprime** [comment]
Let's just leave this for now. We can revisit this if users have a need to persist raw connection strings.. I have a feeling this will come back up.

**Comment by chrisdias** [comment]
@fiveisprime not clear what you mean by "Let's just leave this for now"... what is "this"? :)

The challenge here is that it would be good to let people move between their non CosmosDB connections and their CosmosDB connections.

Can we simply continue to what we do with connection strings today (persist per workspace) and revisit the issue once we have the secure storage API?  

Or, maybe that is what @fiveisprime is suggesting? :)

**Comment by fiveisprime** [comment]
I don't like the idea of storing these in plain text since there may be credentials in the connection strings.

"Leave this for now" was meant as: avoid persisting potentially sensitive information until we have a secure solution or until we find that we have a need and the security concern is invalid (or acceptable by the community's standards).

Sorry that wasn't super clear, Eric asked me for the same clarification 🙍
