### ISSUE TITLE
"Empty" partition key cancels DocDB collection creation. Instead, validate the partitionKey

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#504]
Not a bug, but when creating a collection in a Doc DB database, if you hit enter when prompted for the partition key, it will cancel the create action.  What if we just generated a random key for the user?

**Comment by PrashanthCorp** [comment]
I wouldn't suggest creating a random partition key, as the key would be a field that's present in almost every document. Moreover, we currently don't give the user a way to read what the partition key is. Hence I'd vote for doing  lesser damage. :)

**Comment by EricJizbaMSFT** [comment]
I agree we shouldn't generate a key, but feels like we should allow an empty key. For example, in the portal you're not even prompted for a partition key if you're using a smaller database

**Comment by StephenWeatherford** [comment]
I swear I already opened this issue, but can't find it.  To use an empty key, we have to provide an option to use the "fixed" capacity instead of the "unlimited" capacity.  Agreed we should do it for next version.

Also, I hate the cancel behavior here.  @PrashanthCorp is this our fault or VS Code's fault?

**Comment by StephenWeatherford** [comment]
Found it, it was incorrectly closed...  https://github.com/Microsoft/vscode-cosmosdb/issues/295

Let's use *this* issue to deal with the unexpected cancelation behavior.

**Comment by PrashanthCorp** [comment]
Fixed via #872
