### ISSUE TITLE
Extension stopped working after an upgrade

### ISSUE THREAD

**Issue by aeos** [Microsoft/vscode-cosmosdb#513]
All actions in VSCode now return a command not found error like:
command 'cosmosDB.attachDatabaseAccount' not found

using vscode: 
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T00:27:19.487Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

extension version 0.5.1

**Comment by PrashanthCorp** [comment]
Hi, 
At the points that I've found this error, trying out one of these has worked. Let me know if these work for you: 
1. If you downloaded the VSIX : Instead of running the vsix, install the extension from VSCode using the 'Install from VSIX' command. 
2. Ensuring the [vscode-azure-account](https://github.com/Microsoft/vscode-azure-account) is installed. 
3. Running 'npm install'

**Comment by marcin-chwedczuk-cybervadis** [comment]
I have the same problem after upgrade of VSCode. My solution was to uninstall extension, restart VS, then install it again and restert VSCode again. Then everything worked.

**Comment by PrashanthCorp** [comment]
@marcin-chwedczuk-cybervadis Glad to know it worked! Thanks for letting us know about the issue and how you fixed it!

**Comment by PrashanthCorp** [comment]
@marcin-chwedczuk-cybervadis Glad to know it worked! Thanks for letting us know about the issue and how you fixed it!

**Comment by StephenWeatherford** [comment]
@aeos We'll close this issue for now. Feel free to reactivate if Marcin's solution doesn't help and you still have this problem.  Thanks.
