### ISSUE TITLE
Trying to update MongoDB Document : Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by sinumohan** [Microsoft/vscode-cosmosdb#538]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.update
Error type: Error
Error Message: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

Version: 0.6.0
OS: darwin

**Comment by StephenWeatherford** [comment]
Thanks for reporting.  Is there anything unusual about the document or account that you're aware of or that you suspect might be at issue?  Does it happen for every document you try to update?  Thx.

**Comment by PrashanthCorp** [comment]
Were you dealing with Mongo documents when this error occured? 

I have seen this error before with Mongo documents. If it pertains to mongo, it could be due to a combination of factors - 
1. 12 bytes can be represented with 24 hex characters, so they are equivalent. Mongo's id fields are required to be 12bytes/24hex. Mongo can generate these for you, [called the `_id` or ObjectID](https://docs.mongodb.com/manual/reference/method/ObjectId/)
2. Mongo's `_id` field, which can also be referenced by `id`. See [the code](https://github.com/mongodb/mongoid/blob/master/lib/mongoid/fields.rb#L47) and a [stack overflow thread](https://stackoverflow.com/questions/9694460/difference-between-id-and-id-fields-in-mongodb)

We would appreciate a little more context for the repro. :-)
Let us know if this helps.

**Comment by StephenWeatherford** [comment]
Thanks for reporting, this is being discussed in #534.
