### ISSUE TITLE
how to set authentication (non admin) on attached MongoDB

### ISSUE THREAD

**Issue by davidB** [Microsoft/vscode-cosmosdb#668]
Hi,

I try to connect to a remote MongoDB, I configure the url as `mongodb://<hostname>:<port>` and the db is listed but I see
```
not authorized on admin to execute command { listDatabases: 1 }
```

And that it expected, because I should use an dedicated account "username:password".
I tried `mongodb://<username>:password@<hostname>:<port>` without success.
How can define the authentication to use for connection ?

(Sorry I didn't find the response during search in the issues)

**Comment by thigh** [comment]
Hi @davidB , this looks like a permissions issue on the remote DB.  Do you know if the remote DB is configured to allow your account to query?  "listDatabases" is one of the rights that can be assigned so the error suggests you don't have this right.

If you haven't already, try to connect via the mongo CLI.

**Comment by davidB** [comment]
I'm allowed to connect  with a dedicated user with access only on my db, but I'm not allowed to connect as "admin" without password.
My question is own to define the username and password to use for connection.

(I used this account from my code, and an other client)

**Comment by davidB** [comment]
it works when I define the only db I can see.
```
mongodb://<username>:password@<hostname>:<port>/<db>
```

Sorry for noise, Thanks for your time

**Comment by thigh** [comment]
Excellent!  I think that might be because your user is defined on that DB.  Do you know if your configuration is using an authorization DB?  For instance, my admin DB is used as the authorization source so my mongo DB URL looks like this:

`mongodb://<username>:<password>@<host>:<port>/?authSource=<auth_db_name>`

This allows me to specify the authentication DB in the URL so the driver knows how to authenticate me.  Useful when you want to maintain users and roles in one place.

**Comment by davidB** [comment]
The user/password is not defined into an authorization DB.
