### ISSUE TITLE
failed to connect to server [127.0.0.1:27017] 

### ISSUE THREAD

**Issue by sarancruzer** [Microsoft/vscode-cosmosdb#692]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.7.2
OS: win32

**Comment by PrashanthCorp** [comment]
Hi Saravanan, 

Thanks for reporting the issue! We really appreciate your feedback. 
From a first look, it looks like you're trying to connect to a local mongodb instance. 
Please let us know if [this comment](https://github.com/Microsoft/vscode-cosmosdb/issues/662#issuecomment-395891819) helps. 
It currently looks like this issue is a duplicate of #662.

**Comment by StephenWeatherford** [comment]
@sarancruzer We're going to go ahead and close for now.  If you are still having troubles, feel free to re-open.  Thanks!
