### ISSUE TITLE
[Windows][Mongo] We need a better error message if emulator not started

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-cosmosdb#706]

**Comment by EricJizbaMSFT** [comment]
I'll add that about 30% of all attachEmulator events right now are failures on mac/linux. According to [this](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator), the emulator is only supported on Windows - we should be able to explain that.

**Comment by StephenWeatherford** [comment]
@fiveisprime Should we be removing this menu item on Mac/Linux?

**Comment by fiveisprime** [comment]
Yeah, hide it on macOS and Linux.

**Comment by PrashanthCorp** [comment]
Testing this, I realized this behavior is specifically for Mongo. I changed the title to reflect this. FOr SQL, the behavior is described at #873

**Comment by StephenWeatherford** [comment]
We need the same logic in shell exec.

**Comment by wwlorey** [comment]
> We need the same logic in shell exec.

This appears to be the only unresolved issue here. And it looks like fixing it is out of our control since we just [launch a shell](https://github.com/microsoft/vscode-cosmosdb/blob/wwl/rearrange/src/mongo/registerMongoCommands.ts#L149-L153) and don't have access to any errors that may arise there

**Comment by EricJizbaMSFT** [comment]
Pretty sure it was talking about [this shell](https://github.com/microsoft/vscode-cosmosdb/blob/7d2367133f381871f84a4f09f5003e54b7f78fb9/src/mongo/tree/MongoDatabaseTreeItem.ts#L131). Aka if I have these two commands in a mongo scrapbook:
```
db.inventory.find()

db.getCollection('inventory').find()
```

The second one is sent to the mongo shell because we can't automagically handle it ourselves. I feel like we might have access to the shell output in that case?
