### ISSUE TITLE
Unrecognized child type

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#722]
Repro steps:

db.c.find({"a":[1,2,3]"b":1}) 

Action: vscode.workspace.onDidChangeTextDocument
Error type: AssertionError
Error Message: Unrecognized child type in parse tree.

Version: 0.7.2-alpha
OS: win32

**Comment by PrashanthCorp** [comment]
Looks like this would be fixed with the PR #729 

This is the error I see in the problems tab: 
```
mismatched input '\"b\"' expecting {',', '}'}
```
![image](https://user-images.githubusercontent.com/30420973/42062420-67edd178-7ae2-11e8-9d83-8a3ab59297cf.png)

Expects a comma, and that seems fair. 

The squiggly shows up between `]` and `"b"`. 
![image](https://user-images.githubusercontent.com/30420973/42062396-560063c2-7ae2-11e8-9673-386fae4587c9.png)

HTH.
