### ISSUE TITLE
[Suggestion]Add 'Open' action for 'stored procedures/documents'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#752]
Platforms:Win10/Mac/Linux

Repro Steps:
Right click one stored procedure/document and check the context menu.

Suggestion:
Add 'Open' action for 'stored procedures/documents'. In this case, we can keep multiple tabs open.

Actual:
Only display 'Delete Stored Procedures/Documents'.
![actual](https://user-images.githubusercontent.com/34729092/42273313-6028322c-7f78-11e8-835f-dea91182c49a.PNG)

**Comment by tec-goblin** [comment]
Having two procedures open is very useful. The cause is not so much the lack of Open in the menu (double click should do the same), it's the way the editor identifies what type of file it is showing and what commands should be available. Right now this is based on the name of the tab: it is named always cosmos-stored-procedure.js, regardless of the name of your Sproc. Obviously it's not a great idea to have two tabs named "cosmos-stored-procedure.js".
There might be another way to tell the Editor that it shows a Cosmos Stored Procedure. A name pattern? Attach metadata to the editor? I can have a look but not just yet, I am starting with simpler things first :).

**Comment by PrashanthCorp** [comment]
If you want multiple open stored procedures, we should track it in #581. If you want a context menu item to open Stored Procedures, we can do that too.

**Comment by PrashanthCorp** [comment]
Looks like this is implemented.
