### ISSUE TITLE
Failed to insert document with a period in the key

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#753]
Repro steps:
1. Create a mongo database with a collection named 'test'
1. Run the following from the scrapbook:
```
db.test.insert({
    "address.zipCode": "fda"
})
```

Expected:
The document is successfully inserted

Actual:
Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: key address.zipCode must not contain '.'

Version: 0.8.0
OS: darwin

NOTE: "address.zipCode" is the default shard key in the portal, so feels like we should handle this.

**Comment by PrashanthCorp** [comment]
The error pops up from the mongo library, not us. 

As a parity check, I tried it out on the mongo shell. 
It looks like the mongo shell too doesn't allow it: 
![image](https://user-images.githubusercontent.com/30420973/42350170-2bb55956-8064-11e8-850d-b5e938f4e86f.png)

I agree having periods in a field name for inserts would be nice, but there's not much we can do here atm.

Closing, since we have parity on this use-case.

**Comment by EricJizbaMSFT** [comment]
I agree this might not be the highest priority bug and doesn't need to be addressed immediately, but I think it warrants at least some resolution considering it's a default case from the portal. We should either file a bug on the mongo library to work with dots or file a bug with the portal to change their default example.

**Comment by PrashanthCorp** [comment]
Won't fix pending customer response
