### ISSUE TITLE
Selecting 'Save' pops up an error after closing the document in editor

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-cosmosdb#766]
Repro steps:
1.Drill down from Subscription ->Cosmos DB Account like '0713test'->database->collection->document, then select one document and make changes
2.Click '**x**' to close the document, then make sure that pops up a dialog.
3.Select 'Save' -> 'Upload', then check the result.

Expect:
Succeed to save the file and without any error.

Actual:
Pop up an error dialog though the document can be saved successfully. Please see the below picture.
![save error](https://user-images.githubusercontent.com/37653604/42677556-a2ba107a-866b-11e8-85ab-bf692e46da59.png)

**Comment by tec-goblin** [comment]
Some more details: This behaviour occurs when there's no other editor open.
When there's another editor open, the previous editor before that item has its contents replaced with the closed file's content. That was really funny actually.
I think that's because CosmosEditorManager.updateToCloud unconditionally calls .updateEditor for the activeTextEditor. 
I'll try to send a pull request on that very soon by Sunday.

**Comment by v-haiz** [comment]
@tec-goblin Ok, thanks for your sharing and update.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/818
