### ISSUE TITLE
Add support to execute a stored procedure

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#896]
in the node-documentdb package, the document client class has an endpoint `client.executeStoredProcedure`. We could investigate using that to enable the functionality.

**Comment by tec-goblin** [comment]
Hi, I had this in my wish list :). We'd need a way to request the arguments, a way to show the results, and a way to show statistics (as is the case for graphClient - the main reason why I'd use it outside an application would be to see if it works and the AUs).
If we have all that, then we could extend it (as a different issue) to show similar stats and results from doing any arbitrary query to DocumentDb. That's very useful in order to detect the impact of various alternatives of querying or modelling the data.
Once you start having a plan, feel free to assign me some of the tasks if you want :) - as long as it's not terribly urgent and you can wait for a month.
