### ISSUE TITLE
Problem writing numbers with a fractional part of .0

### ISSUE THREAD

**Issue by codermrrob** [microsoft/vscode-cosmosdb#979]
<Please be sure to remove any private information before submitting.>

Repro steps:
```
db.collection.insert(
{
"tax_rate" : {
      "type" : "number",
       "description" : "invoice line tax rate",
        "enum" : [ 
                0.0, 
                15.0, 
                25.0
        ]
}
})
```

results in the object incorrectly written to database

```
{
"tax_rate" : {
      "type" : "number",
       "description" : "invoice line tax rate",
        "enum" : [ 
                0, 
                15, 
                25
        ]
}
}
```

I store json schemas in my database, the schema includes some enum validation to restrict possible values.

Executing the above insert changes the types from number to integer which is not equivalent.
In my case it causes the schema validation to fail, but it is incorrect in any case.

Regardless of the json schema distraction it is clear that the intention is store a number rather than integer type so I expect the .0 fractional part should be preserved.

Version: 0.9.1
OS: win10Pro

**Comment by PrashanthCorp** [comment]
Unfortunately, this looks like a problem with JSON.parse itself. :/ 
JSON.parse("5.0") returns 5, and that looks like the source of your error. Here's the offending line: 
https://github.com/Microsoft/vscode-cosmosdb/blob/99c83babc28b116fae2e29e5394ae2a808d9a7d2/src/mongo/MongoScrapbook.ts#L303

We tokenize the input to tokens as granular as we can, and then parse that expression tree into an object. At the most basic level of literals, (strings and numbers) we rely on JSON.parse - that handles many of the edge cases we otherwise would have to. If you want more context, check out `src/mongo/scrapbook`. 

Given how fundamental it is and the number of things affected, fixing this would definitely require testing a lot of edge cases. How about I triage this with the team after the holiday break and get back to you on this?

**Comment by codermrrob** [comment]
thanks, glad it is being looked at. Hopefully can be a resolution to this.
